In [2]:
import pandas as pd
import numpy as np

In [4]:
a=pd.read_csv(r'C:\Users\SOMESH\Desktop\Final Year Project\Crop-Datasets-for-All-Indian-States-main\Crop-Datasets-for-All-Indian-States-main\Crops_data.csv')

In [5]:
a

,Dist Code,Year,State Code,State Name,Dist Name,RICE AREA (1000 ha),RICE PRODUCTION (1000 tons),RICE YIELD (Kg per ha),WHEAT AREA (1000 ha),WHEAT PRODUCTION (1000 tons),...,SUGARCANE YIELD (Kg per ha),COTTON AREA (1000 ha),COTTON PRODUCTION (1000 tons),COTTON YIELD (Kg per ha),FRUITS AREA (1000 ha),VEGETABLES AREA (1000 ha),FRUITS AND VEGETABLES AREA (1000 ha),POTATOES AREA (1000 ha),ONION AREA (1000 ha),FODDER AREA (1000 ha)
0,1,2010,14,Chhattisgarh,Durg,777.92,1319.18,1695.77,46.12,45.87,...,256.96,0.00,0.00,0.00,2.00,32.29,34.30,0.11,0.49,0.15
1,1,2011,14,Chhattisgarh,Durg,806.55,1416.48,1756.23,44.98,50.19,...,506.02,0.08,0.02,250.00,0.00,0.00,0.00,0.12,0.54,0.00
2,1,2012,14,Chhattisgarh,Durg,807.07,1534.22,1900.97,43.87,47.69,...,252.98,0.13,0.02,153.85,1.99,33.70,35.69,0.12,0.54,1.32
3,1,2013,14,Chhattisgarh,Durg,819.44,1296.24,1581.86,41.54,43.33,...,237.45,0.05,0.01,200.00,1.90,32.83,34.74,0.11,0.50,0.77
4,1,2014,14,Chhattisgarh,Durg,834.87,1444.24,1729.89,44.25,50.96,...,602.17,0.05,0.02,400.00,0.00,0.00,0.00,0.33,0.51,0.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2479,917,2013,15,Jharkhand,Singhbhum,267.06,579.70,2170.67,1.53,1.85,...,0.00,0.00,0.00,0.00,0.00,9.02,9.03,0.48,0.08,0.00
2480,917,2014,15,Jharkhand,Singhbhum,256.33,586.63,2288.57,5.36,6.65,...,0.00,0.00,0.00,0.00,0.00,8.63,8.64,0.46,0.04,0.00
2481,917,2015,15,Jharkhand,Singhbhum,263.21,264.71,1005.70,1.99,1.82,...,0.00,0.00,0.00,0.00,0.00,6.84,6.85,0.42,0.01,0.00
2482,917,2016,15,Jharkhand,Singhbhum,224.05,319.01,1423.84,0.38,0.83,...,0.00,0.00,0.00,0.00,0.03,6.40,6.43,0.03,0.01,0.00
2483,917,2017,15,Jharkhand,Singhbhum,386.91,669.97,1731.62,0.00,0.00,...,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00

In [7]:
a.shape

(2484, 80)

In [8]:
a.head()

,Dist Code,Year,State Code,State Name,Dist Name,RICE AREA (1000 ha),RICE PRODUCTION (1000 tons),RICE YIELD (Kg per ha),WHEAT AREA (1000 ha),WHEAT PRODUCTION (1000 tons),...,SUGARCANE YIELD (Kg per ha),COTTON AREA (1000 ha),COTTON PRODUCTION (1000 tons),COTTON YIELD (Kg per ha),FRUITS AREA (1000 ha),VEGETABLES AREA (1000 ha),FRUITS AND VEGETABLES AREA (1000 ha),POTATOES AREA (1000 ha),ONION AREA (1000 ha),FODDER AREA (1000 ha)
0,1,2010,14,Chhattisgarh,Durg,777.92,1319.18,1695.77,46.12,45.87,...,256.96,0.00,0.00,0.00,2.00,32.29,34.30,0.11,0.49,0.15
1,1,2011,14,Chhattisgarh,Durg,806.55,1416.48,1756.23,44.98,50.19,...,506.02,0.08,0.02,250.00,0.00,0.00,0.00,0.12,0.54,0.00
2,1,2012,14,Chhattisgarh,Durg,807.07,1534.22,1900.97,43.87,47.69,...,252.98,0.13,0.02,153.85,1.99,33.70,35.69,0.12,0.54,1.32
3,1,2013,14,Chhattisgarh,Durg,819.44,1296.24,1581.86,41.54,43.33,...,237.45,0.05,0.01,200.00,1.90,32.83,34.74,0.11,0.50,0.77
4,1,2014,14,Chhattisgarh,Durg,834.87,1444.24,1729.89,44.25,50.96,...,602.17,0.05,0.02,400.00,0.00,0.00,0.00,0.33,0.51,0.00

In [9]:
a.tail()

,Dist Code,Year,State Code,State Name,Dist Name,RICE AREA (1000 ha),RICE PRODUCTION (1000 tons),RICE YIELD (Kg per ha),WHEAT AREA (1000 ha),WHEAT PRODUCTION (1000 tons),...,SUGARCANE YIELD (Kg per ha),COTTON AREA (1000 ha),COTTON PRODUCTION (1000 tons),COTTON YIELD (Kg per ha),FRUITS AREA (1000 ha),VEGETABLES AREA (1000 ha),FRUITS AND VEGETABLES AREA (1000 ha),POTATOES AREA (1000 ha),ONION AREA (1000 ha),FODDER AREA (1000 ha)
2479,917,2013,15,Jharkhand,Singhbhum,267.06,579.70,2170.67,1.53,1.85,...,0.0,0.0,0.0,0.0,0.00,9.02,9.03,0.48,0.08,0.0
2480,917,2014,15,Jharkhand,Singhbhum,256.33,586.63,2288.57,5.36,6.65,...,0.0,0.0,0.0,0.0,0.00,8.63,8.64,0.46,0.04,0.0
2481,917,2015,15,Jharkhand,Singhbhum,263.21,264.71,1005.70,1.99,1.82,...,0.0,0.0,0.0,0.0,0.00,6.84,6.85,0.42,0.01,0.0
2482,917,2016,15,Jharkhand,Singhbhum,224.05,319.01,1423.84,0.38,0.83,...,0.0,0.0,0.0,0.0,0.03,6.40,6.43,0.03,0.01,0.0
2483,917,2017,15,Jharkhand,Singhbhum,386.91,669.97,1731.62,0.00,0.00,...,0.0,0.0,0.0,0.0,0.00,0.00,0.00,0.00,0.00,0.0

In [10]:
a.isnull().sum().sum()

0

In [11]:
a.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2484 entries, 0 to 2483
Data columns (total 80 columns):
 #   Column                                       Non-Null Count  Dtype
---  ------                                       --------------  -----
 0   Dist Code                                    2484 non-null   int64
 1   Year                                         2484 non-null   int64
 2   State Code                                   2484 non-null   int64
 3   State Name                                   2484 non-null   object
 4   Dist Name                                    2484 non-null   object
 5   RICE AREA (1000 ha)                          2484 non-null   float64
 6   RICE PRODUCTION (1000 tons)                  2484 non-null   float64
 7   RICE YIELD (Kg per ha)                       2484 non-null   float64
 8   WHEAT AREA (1000 ha)                         2484 non-null   float64
 9   WHEAT PRODUCTION (1000 tons)                 2484 non-null   float64
 10  WHEAT YIELD (Kg per ha)                      2484 non-null   float64
 11  KHARIF SORGHUM AREA (1000 ha)                2484 non-null   float64
 12  KHARIF SORGHUM PRODUCTION (1000 tons)        2484 non-null   float64
 13  KHARIF SORGHUM YIELD (Kg per ha)             2484 non-null   float64
 14  RABI SORGHUM AREA (1000 ha)                  2484 non-null   float64
 15  RABI SORGHUM PRODUCTION (1000 tons)          2484 non-null   float64
 16  RABI SORGHUM YIELD (Kg per ha)               2484 non-null   float64
 17  SORGHUM AREA (1000 ha)                       2484 non-null   float64
 18  SORGHUM PRODUCTION (1000 tons)               2484 non-null   float64
 19  SORGHUM YIELD (Kg per ha)                    2484 non-null   float64
 20  PEARL MILLET AREA (1000 ha)                  2484 non-null   float64
 21  PEARL MILLET PRODUCTION (1000 tons)          2484 non-null   float64
 22  PEARL MILLET YIELD (Kg per ha)               2484 non-null   float64
 23  MAIZE AREA (1000 ha)                         2484 non-null   float64
 24  MAIZE PRODUCTION (1000 tons)                 2484 non-null   float64
 25  MAIZE YIELD (Kg per ha)                      2484 non-null   float64
 26  FINGER MILLET AREA (1000 ha)                 2484 non-null   float64
 27  FINGER MILLET PRODUCTION (1000 tons)         2484 non-null   float64
 28  FINGER MILLET YIELD (Kg per ha)              2484 non-null   float64
 29  BARLEY AREA (1000 ha)                        2484 non-null   float64
 30  BARLEY PRODUCTION (1000 tons)                2484 non-null   float64
 31  BARLEY YIELD (Kg per ha)                     2484 non-null   float64
 32  CHICKPEA AREA (1000 ha)                      2484 non-null   float64
 33  CHICKPEA PRODUCTION (1000 tons)              2484 non-null   float64
 34  CHICKPEA YIELD (Kg per ha)                   2484 non-null   float64
 35  PIGEONPEA AREA (1000 ha)                     2484 non-null   float64
 36  PIGEONPEA PRODUCTION (1000 tons)             2484 non-null   float64
 37  PIGEONPEA YIELD (Kg per ha)                  2484 non-null   float64
 38  MINOR PULSES AREA (1000 ha)                  2484 non-null   float64
 39  MINOR PULSES PRODUCTION (1000 tons)          2484 non-null   float64
 40  MINOR PULSES YIELD (Kg per ha)               2484 non-null   float64
 41  GROUNDNUT AREA (1000 ha)                     2484 non-null   float64
 42  GROUNDNUT PRODUCTION (1000 tons)             2484 non-null   float64
 43  GROUNDNUT YIELD (Kg per ha)                  2484 non-null   float64
 44  SESAMUM AREA (1000 ha)                       2484 non-null   float64
 45  SESAMUM PRODUCTION (1000 tons)               2484 non-null   float64
 46  SESAMUM YIELD (Kg per ha)                    2484 non-null   float64
 47  RAPESEED AND MUSTARD AREA (1000 ha)          2484 non-null   float64
 48  RAPESEED AND MUSTARD PRODUCTION (1000 tons)  2484 non-null   float64
 49  RAPESEED AND MUSTARD YIELD (Kg per ha)       2484 non-null   float64
 50  SAFFLOWER AREA (1000 ha)                     2484 non-null   float64
 51  SAFFLOWER PRODUCTION (1000 tons)             2484 non-null   float64
 52  SAFFLOWER YIELD (Kg per ha)                  2484 non-null   float64
 53  CASTOR AREA (1000 ha)                        2484 non-null   float64
 54  CASTOR PRODUCTION (1000 tons)                2484 non-null   float64
 55  CASTOR YIELD (Kg per ha)                     2484 non-null   float64
 56  LINSEED AREA (1000 ha)                       2484 non-null   float64
 57  LINSEED PRODUCTION (1000 tons)               2484 non-null   float64
 58  LINSEED YIELD (Kg per ha)                    2484 non-null   float64
 59  SUNFLOWER AREA (1000 ha)                     2484 non-null   float64
 60  SUNFLOWER PRODUCTION (1000 tons)             2484 non-null   float64
 61  SUNFLOWER YIELD (Kg per ha)                  2484 non-null   float64
 62  SOYABEAN AREA (1000 ha)                      2484 non-null   float64
 63  SOYABEAN PRODUCTION (1000 tons)              2484 non-null   float64
 64  SOYABEAN YIELD (Kg per ha)                   2484 non-null   float64
 65  OILSEEDS AREA (1000 ha)                      2484 non-null   float64
 66  OILSEEDS PRODUCTION (1000 tons)              2484 non-null   float64
 67  OILSEEDS YIELD (Kg per ha)                   2484 non-null   float64
 68  SUGARCANE AREA (1000 ha)                     2484 non-null   float64
 69  SUGARCANE PRODUCTION (1000 tons)             2484 non-null   float64
 70  SUGARCANE YIELD (Kg per ha)                  2484 non-null   float64
 71  COTTON AREA (1000 ha)                        2484 non-null   float64
 72  COTTON PRODUCTION (1000 tons)                2484 non-null   float64
 73  COTTON YIELD (Kg per ha)                     2484 non-null   float64
 74  FRUITS AREA (1000 ha)                        2484 non-null   float64
 75  VEGETABLES AREA (1000 ha)                    2484 non-null   float64
 76  FRUITS AND VEGETABLES AREA (1000 ha)         2484 non-null   float64
 77  POTATOES AREA (1000 ha)                      2484 non-null   float64
 78  ONION AREA (1000 ha)                         2484 non-null   float64
 79  FODDER AREA (1000 ha)                        2484 non-null   float64
dtypes: float64(75), int64(3), object(2)
memory usage: 1.5+ MB